### ISSUE TITLE
Few trailing MQTT messages get lost

### ISSUE THREAD

**Issue by oliviercommelarbre** [MarshFlattsFarm/myUplink-API#1]
Dear David, i found a little bug in the script which makes that, at least when using mosquitto as mqtt broker, the last x or so MQTT messages at the end of the long list after the pool from MyUplink get lost. Another symptom is that it leaves an error in the mosquitto log systematically (mosquitto logged error message is "Socket error on client myUplink2MQTT, disconnecting.")
The correction is very simple. It is on the one before last line of the script, just adding the missing parenthesis ('()') to the loop_stop call:

mqtt_client.loop_stop()

**Comment by MarshFlattsFarm** [comment]
Many thanks for finding and reporting this issue Olivier. I've corrected this in the example script.

**Comment by oliviercommelarbre** [comment]
my pleasure! thanks for the kind feedback
